# -*- coding: utf-8 -*-
"""svm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MFz-7Xv9_ZjwTI1KWdpdODbTxgYgQ0k6
"""

# ============================================
# SPAM DETECTION USING SVM (Google Colab)
# ============================================

# Step 1: Upload Dataset
from google.colab import files
uploaded = files.upload()

# Step 2: Import Libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Step 3: Load Dataset
df = pd.read_csv("spam.csv", encoding="latin1")

# Step 4: Keep Required Columns
df = df[['v1', 'v2']]

# Rename Columns
df.columns = ['spam', 'text']

# Convert Labels
df['spam'] = df['spam'].map({
    'ham': 0,
    'spam': 1
})

# Step 5: Display Dataset
print("First 5 Rows:")
print(df.head())

print("\nDataset Shape:", df.shape)

print("\nMissing Values:")
print(df.isnull().sum())

# Step 6: Remove Missing Values
df.dropna(inplace=True)

# Step 7: Features and Labels
X = df['text']
y = df['spam']

# Step 8: Convert Text into TF-IDF Features
vectorizer = TfidfVectorizer(
    stop_words='english',
    ngram_range=(1,2),
    min_df=2
)

X = vectorizer.fit_transform(X)

# Step 9: Split Dataset
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# Step 10: Train SVM Model
model = LinearSVC(random_state=42)
model.fit(X_train, y_train)

# Step 11: Predict Test Data
y_pred = model.predict(X_test)

# Step 12: Accuracy
accuracy = accuracy_score(y_test, y_pred)

print("\nAccuracy:", round(accuracy*100,2), "%")

# Step 13: Classification Report
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))

# Step 14: Confusion Matrix
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

# ============================================
# Step 15: Test New Email
# ============================================

new_email = [
"""
Subject: Project Meeting Reminder

Hi Team,

This is a reminder that our project meeting is scheduled for tomorrow at 10:00 AM in the conference room.

Please bring your progress reports and be prepared to discuss the tasks completed this week. If you are unable to attend, kindly inform the team in advance.

Thank you.

Best regards,
Niveesh
Project Coordinator
"""
]

new_email_vector = vectorizer.transform(new_email)

prediction = model.predict(new_email_vector)

print("\nPrediction Value:", prediction[0])

if prediction[0] == 1:
    print("Prediction: Spam Email")
else:
    print("Prediction: Not Spam Email")